### ISSUE TITLE
code/data from Angela

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MultiAssayExperiment-NCI60#1]
"multiAssayExperiment - NCI-60 instance" email from Mar 19. FYI @LiNk-NY @schifferl. 

[multiassayexperimentnci60instance.zip](https://github.com/waldronlab/MultiAssayExperiment-NCI60/files/350549/multiassayexperimentnci60instance.zip)

**Comment by LiNk-NY** [comment]
Added to the repo
